# Generated by Django 2.0.4 on 2018-05-02 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_remove_profile_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messenger',
            new_name='Messanger',
        ),
    ]
