# Generated by Django 2.0.4 on 2018-05-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180502_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messanger',
            name='profile',
        ),
    ]
