# Generated by Django 2.0.4 on 2018-04-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('bed', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('flat_area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=130)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=10)),
                ('brand', models.CharField(max_length=120)),
                ('desktop', models.BooleanField(default=False)),
                ('laptop', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('monitor', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=100)),
                ('configuration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('warrenty', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('study_item', models.CharField(choices=[('bangla', 'bangla'), ('english', 'english')], max_length=10)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=10)),
                ('brand', models.CharField(max_length=120)),
                ('thtree_g', models.BooleanField(default=False)),
                ('four_g', models.BooleanField(default=False)),
                ('touch_screen', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=10)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District')),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='service_image')),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=10)),
                ('brand', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
        ),
        migrations.AddField(
            model_name='computing',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.District'),
        ),
    ]
