# Generated by Django 2.0.4 on 2018-04-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='category',
            field=models.ForeignKey(default='Mobile Phone', on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
    ]
