# Generated by Django 2.0.4 on 2018-04-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180429_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AlterField(
            model_name='computing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AlterField(
            model_name='others',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AlterField(
            model_name='television',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
    ]
