# Generated by Django 2.0.4 on 2018-04-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180429_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computing',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='television',
            name='division',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='service.Division'),
            preserve_default=False,
        ),
    ]
