# Generated by Django 2.0.4 on 2018-05-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20180501_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.Category'),
        ),
    ]
