# Generated by Django 2.0.4 on 2018-04-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='service',
        ),
    ]
